const COMMENTS = [
  { score: 200, comment: "Great start! Every kill counts in this mission." },
  {
    score: 400,
    comment: "Keep it up! The enemies won’t eliminate themselves!",
  },
  { score: 600, comment: "Excellent work! The mission is underway." },
  { score: 800, comment: "Keep racking up points! You’re a killing machine." },
  { score: 1000, comment: "Incredible! Don’t stop now!" },
  { score: 1200, comment: "You’re on a roll! Keep going, soldier!" },
  {
    score: 1400,
    comment: "Very good! Every enemy eliminated brings you closer to victory.",
  },
  { score: 1600, comment: "You’re a hero! Keep it up and show your strength!" },
  { score: 1800, comment: "Impressive work, keep it up!" },
  { score: 2000, comment: "Keep up the pace!" },
  { score: 2200, comment: "You’re a legend on the battlefield!" },
  {
    score: 2400,
    comment: "Great job! You’re about to advance to the next level.",
  },
  { score: 2600, comment: "Level 2 unlocked! Keep going, soldier!" },
  { score: 2800, comment: "Excellent! You’re showing great skill!" },
  { score: 3000, comment: "Keep eliminating enemies! Victory is near!" },
  { score: 3200, comment: "Great! You’re advancing quickly." },
  { score: 3400, comment: "Keep it up!" },
  {
    score: 3600,
    comment: "You’re unstoppable! The mission is becoming more challenging!",
  },
  { score: 3800, comment: "You’re getting stronger! Don’t give up!" },
  { score: 4000, comment: "A true hero of the battle!" },
  { score: 4200, comment: "Your prowess is amazing! Keep it up!" },
  { score: 4500, comment: "Fantastic! Keep racking up points!" },
  { score: 4700, comment: "You’re surpassing all expectations!" },
  { score: 5000, comment: "Level 3 unlocked! You’re an expert enemy hunter!" },
  { score: 5200, comment: "Nothing can stop you!" },
  { score: 5500, comment: "Incredible! Your skills are out of this world!" },
  { score: 5700, comment: "Keep it up! Victory is near!" },
  { score: 6000, comment: "You’re an inspiration to all of us!" },
  { score: 6500, comment: "Your perseverance is admirable!" },
  {
    score: 7000,
    comment: "Impressive! Your name will be remembered in history!",
  },
  { score: 7500, comment: "Every kill counts! Keep racking them up!" },
  { score: 8000, comment: "You’re the best soldier we’ve ever seen!" },
  { score: 8500, comment: "Your bravery is unmatched!" },
  { score: 9000, comment: "A true master of battle!" },
  { score: 9500, comment: "Nothing can halt your advance!" },
  { score: 10000, comment: "Level 4 unlocked! You’re a living legend!" },
  { score: 10500, comment: "Your name will be remembered for generations!" },
  { score: 11000, comment: "You’re the hero we all need!" },
  { score: 11500, comment: "Keep it up! Total victory is within your reach!" },
  {
    score: 12000,
    comment: "Level 5 unlocked! You’re the king of the battlefield!",
  },
  { score: 12500, comment: "No one can match your prowess!" },
  { score: 13000, comment: "Your legend spreads throughout the kingdom!" },
  { score: 13500, comment: "A warrior without equal!" },
  { score: 14000, comment: "The battlefield is yours!" },
  { score: 14500, comment: "You’re an unstoppable force!" },
  { score: 15000, comment: "Level 6 unlocked! You’re invincible!" },
];
