const NPCS = [
  {
    id: 1,
    name: "pirate1",
    backgroundImage: "pirate1.gif",
    speed: "5s",
    delay: "1s",
    points: 1000,
  },
  {
    id: 2,
    name: "pirate2",
    backgroundImage: "pirate2.gif",
    speed: "5s",
    delay: "3s",
    points: 1000,
  },
  {
    id: 3,
    name: "pirate3",
    backgroundImage: "pirate3.gif",
    speed: "6s",
    delay: "5s",
    points: 1000,
  },
  {
    id: 4,
    name: "pirate4",
    backgroundImage: "pirate4.gif",
    speed: "3s",
    delay: "8s",
    points: 1000,
  },
  {
    id: 5,
    name: "innocent1",
    backgroundImage: "innocent1.gif",
    speed: "3s",
    delay: "6s",
    points: 1000,
  },
];
