const NPCS = [
  {
    id: 1,
    name: "enemy1",
    backgroundImage: "kamikaze.gif",
    speed: "5s",
    delay: "1s",
    points: 1000,
  },
  {
    id: 2,
    name: "enemy2",
    backgroundImage: "momia.gif",
    speed: "7s",
    delay: "3s",
    points: 1000,
  },
  {
    id: 3,
    name: "enemy3",
    backgroundImage: "zombi.gif",
    speed: "6s",
    delay: "5s",
    points: 1000,
  },
  {
    id: 4,
    name: "enemy4",
    backgroundImage: "zombi.gif",
    speed: "3s",
    delay: "6s",
    points: 1000,
  },
  {
    id: 5,
    name: "enemy5",
    backgroundImage: "zombi.gif",
    speed: "3s",
    delay: "8s",
    points: 1000,
  },
];
